var labels = {
  "beaver": "Animals",
  "dolphin": "Animals",
  "otter": "Animals",
  "seal": "Animals",
  "whale": "Animals",
  "aquarium fish": "Animals",
  "flatfish": "Animals",
  "ray": "Animals",
  "shark": "Animals",
  "trout": "Animals",
  "bee": "Animals",
  "beetle": "Animals",
  "butterfly": "Animals",
  "caterpillar": "Animals",
  "cockroach": "Animals",
  "bear": "Animals",
  "leopard": "Animals",
  "lion": "Animals",
  "tiger": "Animals",
  "wolf": "Animals",
  "	orchids": "Flowers",
  "poppies": "Flowers",
  "roses": "Flowers",
  "sunflowers": "Flowers",
  "tulips": "Flowers",
  "bottles": "Object",
  "bowls": "Object",
  "cans": "Object",
  "cups": "Object",
  "plates": "Object",
  "apples": "Food",
  "mushrooms": "Food",
  "oranges": "Food",
  "pears": "Food",
  "sweet peppers": "Food",
  "clock": "Devices",
  "computer keyboard": "Devices",
  "lamp": "Devices",
  "telephone": "Devices",
  "television": "Devices",
  "bed": "Furniture",
  "chair": "Furniture",
  "couch": "Furniture",
  "table": "Furniture",
  "wardrobe": "Furniture"
};
